### ISSUE TITLE
Please enable https for the API

### ISSUE THREAD

**Issue by tdelmas** [boyter/searchcode#26]
An https webpage can't call the API because it's redirected to an insecure (http) uri.

**Comment by boyter** [comment]
Yes I had to switch over to http for the moment because my https cert is having issues and im unable to get it to meet the google standards. Its on the list of things to do.

Another issue is that almost no ad networks work with https and changing personal issues mean I need to get this to pay its own way.

I think I will enable https for the api and leave the rest as http.

Is it possible to wait for day on this? I should be able to do that sometime tonight my time.

**Comment by tdelmas** [comment]
Sure, of course, no rush, really !
For the cert, https://startssl.com can provide them for free, and they meet google standards (I guess you talk about sha1...)
And instead of ads, maybe you can try something like https://flattr.com ?

**Comment by boyter** [comment]
Sorry about the bother. I should have realised what moving to http would do.

Sounds like an idea. I will try out startssl and see if I can get it going. 

I thought about flattr.com... I just have a feeling very few people will actually donate. I will give it a trial run over a few months though. If it can pay for hosting I would be very happy.

**Comment by boyter** [comment]
Done and done. I poked around where I got the original ssl cert and just reissued it using sha2 to solve the issue. A bit easier then trying to move over to startssl since I already had the processes set up to take care of it.

Let me know if there are any issues on your end.

Also added one of those flattr.com buttons on a few of the pages. Hopefully something will come of it. I would be very happy if it could pay for hosting costs.
