### ISSUE TITLE
Allow to search through SPDX by SSDEEP hash with similarity threshold

### ISSUE THREAD

**Issue by sschuberth** [boyter/searchcode#29]
It would be awesome if SPDX could not only be searched by MD5/SHA1, but also by SSDEEP with a given similarity threshold. Given the SSDEEP hash of a local file, that way one could easily determine whether that file is derived from free software code.

**Comment by boyter** [comment]
Yes I can see that being quite useful. Interestingly I actually have something similar already inside the bowels of searchcode which is how it works out which source code is similar such as on this page, note the 100 matches button https://searchcode.com/codesearch/view/21207942/

It uses my own implementation however as SSDEEP as far as I could tell requires a full scan every time a request like this comes up. My one is fixed and indexable, but presumably not as accurate.

Do you think there would be a way to index the SSDEEP? My understanding was that different but similar files would produce slightly different results making it harder to do matches on.

**Comment by sschuberth** [comment]
I'm new to SSDEEP and fuzzy hashes in general, but guessing from the [man page](http://ssdeep.sourceforge.net/manpage.html) to SSDEEP's command line tool it does not require a full scan for each request: Given a list of known hashes and the hash to a file to search for, you could use the `-k` argument to quickly find similar files.

However, I'm not sure if there's an efficient way to match a given hash to a huge set of known hashes. I'd be surprised if the SSDEEP command line tool just iterates through all known hashes to match them to the given hash, but I have not looked at the source code.

On the other hand, maybe this is why [TripleCheck switched from SSDEPP to TLSH](http://nunobrito1981.blogspot.de/2015/04/ssdeep-in-java.html?google_comment_id=z132vnvynravd54wx04cghihiwbkgzlqhsg0k). @nunobrito, can give us a glue? The comments in your blog seem to indicate that you are working on indexing TLSH hashes because it was too hard to do with SSDEEP?

**Comment by boyter** [comment]
Yes, thats still a problem though. I think there are about 100,000,000 files in searchcode at the moment, and once the full set of SSDEEP's are calculated thats an impossible number unless there is greater efficiency given the hardware budget I have to play with.

I remember reading that from @nunobrito it sounded similar to what I implemented actually but I would be curious to know more.

**Comment by maxbrito** [comment]
SSDEEP was not very efficient (similarity and speed-wise). We tried hard to push more performance, this was documented at: http://www.syssec-project.eu/m/page-media/3/breitinge-ifip-wg11.9-2013.pdf and just got worse when proven that similarity-wise, it was not so accurate: http://www.syssec-project.eu/m/page-media/3/breitinge-ifip-wg11.9-2013.pdf

Breitinge was living here in Darmstadt at the time, later moved to Canada. In the meanwhile we've moved internally to TLSH because the algorithm was lighter (computation-wise) and feasible to push performance with a java implementation. Our archive has >trillion files, we extract from this set 600M relevant signatures and perform TLSH comparison over the set. On our case each file compared takes a few minutes on a normal laptop (i7, 8Gb RAM, 1Tb HDD) to go through the corpus.

We have on the roadmap to include TLSH on the triplecheck report (users don't mind waiting a few hours when needed) but still have other parts of the software that require attention at the moment.

**Comment by boyter** [comment]
A few minutes really is a non starter sadly. 

I will have a poke with the implementation. I may be able to come up with some ideas on how to speed things up. One idea may be to do a wildcard search against SSDEEP since from memory the last few characters are the ones that change the most when files diverge. Knowing where to put a strategically placed \* might be a solution that works well enough.

**Comment by maxbrito** [comment]
Yes. Could be worth to try. Comparisons against a large single block of signatures is frustrating. I'm grouping files according to extension and this speeds up comparison because now we compare against smaller blocks. Still, no guarantees that the extension is indeed correct (in case someone changes it).

**Comment by boyter** [comment]
So... in order to actually be able to focus on searchcode SPDX support was sadly dropped. 

Something I may look into at a later date though. As such closing.
