### ISSUE TITLE
No results found :(

### ISSUE THREAD

**Issue by styfle** [boyter/searchcode#33]
My query: https://searchcode.com/?q=Copee.toClipboard
My repo: https://github.com/styfle/copee/blob/master/copee.js

Any idea why this is not indexed?

**Comment by boyter** [comment]
I had a look in the database, and its just because I haven't pinged the Github API recently to pick it up. I tend to focus more on other providers like bitbucket since they don't have their own search at the moment. Currently processing gitlab. 

Ill add it in so it gets picked up once the 100,000 or so repo's from gitlab are picked up.

**Comment by styfle** [comment]
:+1:

**Comment by boyter** [comment]
Just letting you know it has been processed (the code is in the right place) and should appear in the index in the next few days.

**Comment by boyter** [comment]
https://searchcode.com/?q=Copee.toClipboard

Now resolves with 6 results :)

**Comment by styfle** [comment]
Looks good, thanks :100:
